### ISSUE TITLE
allow strings as well as array for run

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/donkey-make#9]
so

````yaml
gen_auth_link:
  run: |
    import json, os
    print('this')
    print('that')
  executable: python
```
Works
